name = "bateria_gleam"
version = "1.0.0"
target = "javascript"

[dependencies]
gleam_json = "1.0.1"
gleam_stdlib = "~> 0.36"
lustre = "~> 4.0"
lustre_ui = "~> 0.4"
glint = ">= 1.0.1 and < 2.0.0"
catppuccin = ">= 3.0.5 and < 4.0.0"
gleam_community_colour = ">= 1.4.0 and < 2.0.0"
sketch_lustre = ">= 1.0.0 and < 2.0.0"
sketch = "3.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
lustre_dev_tools = ">= 1.5.0 and < 2.0.0"
